name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
