name: Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    name: Release Builds
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - name: Release Builds
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            release.zip
